spring:
  datasource:
    url: jdbc:mysql://10.9.20.210:3306/scds_local?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123
    # MySQL8.0的驱动，使用com.mysql.cj.jdbc.Driver这个，而其他则使用com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver

# SpringBoot2.x Version Start Log Print
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace
# Redis Start
# spring.redis.host=localhost
# spring.redis.port=6379
# spring.redis.lettuce.pool.max-idle=8
# spring.redis.lettuce.pool.max-active=8
# spring.redis.lettuce.pool.max-wait=-1ms
# spring.redis.lettuce.pool.min-idle=0
# spring.redis.lettuce.shutdown-timeout=100ms
